# Generated by Django 3.2.16 on 2025-05-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('named_url', models.CharField(blank=True, help_text='Named URL from your urls.py file', max_length=200, verbose_name='named URL')),
                ('url', models.CharField(blank=True, help_text='Relative path (e.g. /about/) or absolute URL', max_length=200, verbose_name='url')),
                ('menu_name', models.CharField(help_text='Name of the menu this item belongs to', max_length=50, verbose_name='menu name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='parent item')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
                'ordering': ['order'],
            },
        ),
    ]
